tensor.scatter_, tensor.gather_ 와 같은 함수에 익숙해져야 한다. 

self[index[i][j][k]][j][k] = src[i][j][k]  # if dim == 0
self[i][index[i][j][k]][k] = src[i][j][k]  # if dim == 1
self[i][j][index[i][j][k]] = src[i][j][k]  # if dim == 2

위의 내용을 개념화 하면 해당 dim의 인덱스에 해당되는 값을 src에서 값을 가져와 지정한다. index의 모양을 따라 순회하는 루프들에서 src에서 값을 루프의 i, j, k 값에서 얻어온다.  

In [1]:
import torch 

In [4]:
src = torch.arange(1, 11).reshape((2, 5))
print(src)

index = torch.tensor([[0, 1, 2, 0]])
s1 = torch.zeros(3, 5, dtype=src.dtype).scatter_(0, index, src)
print(f"s1: {s1}") 

index = torch.tensor([[0, 1, 2], [0, 1, 4]])
s2 = torch.zeros(3, 5, dtype=src.dtype).scatter_(1, index, src)
print(s2)

s3 = torch.full((2, 4), 2.).scatter_(1, torch.tensor([[2], [3]]),
            1.23, reduce='multiply')
print(s3)

s4 = torch.full((2, 4), 2.).scatter_(1, torch.tensor([[2], [3]]),
            1.23, reduce='add')
print(s4)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
s1: tensor([[1, 0, 0, 4, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0]])
tensor([[1, 2, 3, 0, 0],
        [6, 7, 0, 0, 8],
        [0, 0, 0, 0, 0]])
tensor([[2.0000, 2.0000, 2.4600, 2.0000],
        [2.0000, 2.0000, 2.0000, 2.4600]])
tensor([[2.0000, 2.0000, 3.2300, 2.0000],
        [2.0000, 2.0000, 2.0000, 3.2300]])
