In [1]:
import torch 
import numpy as np

In [5]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [6]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [8]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
print(f"Random Tensor: \n {rand_tensor} \n")

Random Tensor: 
 tensor([[0.4071, 0.8868, 0.3650],
        [0.1471, 0.6919, 0.7687]]) 



In [10]:
x_tensor = torch.rand(3, 4, 5)
x_tensor

tensor([[[0.1356, 0.5843, 0.6453, 0.1725, 0.3587],
         [0.3757, 0.8494, 0.3312, 0.0866, 0.3785],
         [0.0042, 0.7160, 0.7387, 0.0427, 0.1618],
         [0.7134, 0.4832, 0.5132, 0.1932, 0.9411]],

        [[0.2701, 0.6881, 0.8999, 0.1474, 0.8620],
         [0.7011, 0.1017, 0.2437, 0.4049, 0.1273],
         [0.4225, 0.2364, 0.7125, 0.6734, 0.7771],
         [0.8934, 0.4540, 0.4885, 0.0316, 0.3874]],

        [[0.6310, 0.9250, 0.9029, 0.3771, 0.6711],
         [0.0085, 0.9542, 0.8748, 0.6595, 0.4901],
         [0.9397, 0.4097, 0.6359, 0.6798, 0.3007],
         [0.4223, 0.6257, 0.0424, 0.0411, 0.7058]]])

In [11]:
tensor = torch.ones(4, 4)
tensor[:, 1] = 0
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [18]:
target = torch.zeros(4, 1)
t_1 = torch.cat([tensor, target], dim=1)
t_1

tensor([[1., 0., 1., 1., 0.],
        [1., 0., 1., 1., 0.],
        [1., 0., 1., 1., 0.],
        [1., 0., 1., 1., 0.]])